ABBREVIATIONS: dict[str, str] = {
    "BP": "Blood Pressure",
    "HR": "Heart Rate",
    "RR": "Respiratory Rate",
    "SpO2": "Oxygen Saturation",
    "BMI": "Body Mass Index",
    "FBS": "Fasting Blood Sugar",
    "PPBS": "Post-Prandial Blood Sugar",
    "RBS": "Random Blood Sugar",
    "HbA1c": "Glycated Hemoglobin",
    "TC": "Total Cholesterol",
    "HDL": "High-Density Lipoprotein Cholesterol",
    "LDL": "Low-Density Lipoprotein Cholesterol",
    "TG": "Triglycerides",
    "TSH": "Thyroid Stimulating Hormone",
    "T3": "Triiodothyronine",
    "T4": "Thyroxine",
    "Hb": "Hemoglobin",
    "WBC": "White Blood Cell Count",
    "RBC": "Red Blood Cell Count",
    "PLT": "Platelet Count",
    "ESR": "Erythrocyte Sedimentation Rate",
    "CRP": "C-Reactive Protein",
    "BUN": "Blood Urea Nitrogen",
    "Cr": "Creatinine",
    "GFR": "Glomerular Filtration Rate",
    "eGFR": "Estimated Glomerular Filtration Rate",
    "ALT": "Alanine Aminotransferase",
    "AST": "Aspartate Aminotransferase",
    "ALP": "Alkaline Phosphatase",
    "GGT": "Gamma-Glutamyl Transferase",
    "Na": "Sodium",
    "K": "Potassium",
    "Ca": "Calcium",
    "Mg": "Magnesium",
    "Fe": "Iron",
    "TIBC": "Total Iron-Binding Capacity",
    "Vit D": "Vitamin D",
    "Vit B12": "Vitamin B12",
    "ECG": "Electrocardiogram",
    "EKG": "Electrocardiogram",
    "CBC": "Complete Blood Count",
    "LFT": "Liver Function Test",
    "KFT": "Kidney Function Test",
    "RFT": "Renal Function Test",
    "TFT": "Thyroid Function Test",
    "UTI": "Urinary Tract Infection",
    "COPD": "Chronic Obstructive Pulmonary Disease",
    "CAD": "Coronary Artery Disease",
    "CHF": "Congestive Heart Failure",
    "MI": "Myocardial Infarction",
    "CVA": "Cerebrovascular Accident (Stroke)",
    "DM": "Diabetes Mellitus",
    "HTN": "Hypertension",
    "GERD": "Gastroesophageal Reflux Disease",
    "OA": "Osteoarthritis",
    "RA": "Rheumatoid Arthritis",
    "CKD": "Chronic Kidney Disease",
    "PCOS": "Polycystic Ovary Syndrome",
    "DVT": "Deep Vein Thrombosis",
    "PE": "Pulmonary Embolism",
    "SOB": "Shortness of Breath",
    "DOE": "Dyspnea on Exertion",
    "N/V": "Nausea/Vomiting",
    "HA": "Headache",
    "Rx": "Prescription/Treatment",
    "Dx": "Diagnosis",
    "Hx": "History",
    "Tx": "Treatment",
    "Sx": "Symptoms",
    "Fx": "Fracture",
    "PRN": "As Needed",
    "BID": "Twice Daily",
    "TID": "Three Times Daily",
    "QID": "Four Times Daily",
    "QD": "Once Daily",
    "PO": "By Mouth",
    "IV": "Intravenous",
    "IM": "Intramuscular",
    "SC": "Subcutaneous",
}


def expand_abbreviations(text: str) -> str:
    """Replace known medical abbreviations with full forms in text."""
    result = text
    for abbr, expansion in sorted(ABBREVIATIONS.items(), key=lambda x: -len(x[0])):
        import re
        pattern = re.compile(rf"\b{re.escape(abbr)}\b", re.IGNORECASE)
        result = pattern.sub(f"{expansion} ({abbr})", result)
    return result
